################ MINUUR #############################
    # Microbial INsight Using Unmapped Reads
    # Author: Aidan Foo
    # Email: 248064@lstmed.ac.uk
    # Version: v0.1
#####################################################


from snakemake.utils import validate
import pandas as pd
import os


configfile: "../config/config.yaml"


sample_list = (
    pd.read_csv(config["samples"], sep = "\t", dtype = {"sampleID": str})
    .set_index(["sampleID"], drop = False)
    .sort_index()
)


samples = sample_list["sampleID"].tolist()

include: "rules/01_ReadQc.smk"
include: "rules/02a_BamProcessFromFastq.smk"
include: "rules/02b_BamProcessRaw.smk"
include: "rules/03_ReadClassification.smk"
include: "rules/Assembly.smk"
include: "rules/MapCoverageBin.smk"
include: "rules/BinQA.smk"
include: "rules/ReadFunction.smk"
include: "rules/Functions.smk"


rule all:
    """
        Run the whole pipeline according to parameters set in ../config/config.yaml
    """
    input: 
        RunPipeline,

