################ MINUUR #############################
    # Microbial INsight Using Unmapped Reads
    # Author: Aidan Foo
    # Email: 248064@lstmed.ac.uk
    # Version: v0.1
#####################################################

# Samples: provide file path to the samples names here
samples: ../config/samples_fastq.tsv

# Kraken Database: provide file path to your kraken database here
kraken_db_location: ../resources/kraken_db/

# FASTQ Processing
  # Activate = True to: 
    # Perform QC and Trimming on Raw Fastq
    # Remove Host Associated Reads from Raw Fastq
    # Convert Raw FASTQ to BAM for Processing Steps
    # If you have Raw BAM files: 
    # QC: Activate = False
    # RemoveHostFromFastqGz: Activate = False
    # Moves the pipeline to: "ProcessBams"
input_type: 
  fastq: True
  bam: False

# Perform Quality control on Raw Fastq Reads
# Perofrm trimming using cutadapt. Input trimming parameters as shown below
QC: 
  Activate: True
  CutadaptParams: "--minimum-length 50 -q 30"

# Remove HostReads from Fastq Files and convert to BAM
RemoveHostFromFastqGz: 
  Activate: True
  Threads: 12
  # Give path to Bowtie2 indexed host genome
  ContaminantIndex: ../resources/aedes_ref/aedes_aegypti_idx
  AlignmentSensitivty: "--sensitive-local"
  
# Generate statistics and extract unmapped reads from BAM file
ProcessBam:
  Activate: True
  # Activate if input was Fastq (prior). If Input is bam then FromFastq = False
  FromFastq: True

# READ CLASSIFICATION 
  # Perform read classification with Kraken2 and MetaPhlAn3 on unmapped reads 
  # Input are QC trimmed unmapped reads processed above

# Classify Unmapped Reads with Kraken
KrakenClassification:
  Activate: True
  Threads: 20
  # Confidence score between 0-1 (0 = default, 1 = very stringent)
  ConfidenceScore: 0

# Generate Clean Kraken Summaries + Plots
KrakenSummaries: 
  Activate: True 
  # Set threshold for read count for genus heatmap
  GenusReadThreshold: 6000
  # Set threshold for read count for species heatmap
  SpeciesReadThreshold: 10000
  # Set threshold for read count for stratified species heatmap 
  StratThreshold: 10000
  # TRUE = standard kraken database
  # FALSE = custom kraken database
  KrakenDbStandard: True

# Extract a taxon/phylogeny of your choosing
  # Extract kraken associated reads for a group of taxa 
  # Can be used either for the Users other downstream analysis steps or as input for metagenome assembly stage 
  # Output = paired fastq file of specific taxa
ExtractKrakenTaxa: 
  Activate: True
  # Place TaxID number here (e.g. Extract bacteria = 2)
  taxon_choice: "2"

# Perform Baysian reestiamation of Kraken Classified Reads using Bracken
BrackenReestimation:
  Activate: True
  # Provide path to Bracken built db
  BrakenDb: ../resources/kraken_db/
  # Choose classification level, S = species, G = genus etc
  ClassificationLvl: 'S'
  DistributionThresh: 10
  # Set plot threshold
  PlotThreshold: 10000

# Perform Read Classification with MetaPhlAn3
MetaphlanClassification:
  Activate: True
  # Provide path to MetaPhlAn3 database
  Database: /home/db/User_db/metaphlan_db
  # Generate clean metaphlan tables + plots
  CleanMetaphlanReport: True
  NProc: 8

# FUNCTIONAL PROFILING OF READS
# Perform Functional Profiling of reads with Humann3?
HumannAnalysis:
  Activate: True
  # Path to nucleotide database
  NTDatabase: ../resources/chocophlan/
  # Path to protein database
  ProtDatabase: ../resources/uniref/
  Threads: 20

# Rename humann output to alternative naming convention
RenameHumannGeneNames: 
  Activate: True
  Rename: /home/db/User_dbs/aidan_foo/utility_mapping/map_uniref90_name.txt.bz2 

# Extract function: extract an identified function of choosing 
GetBiologicalProcess:   
  Activate: False
  Process: 
    siderophore: "siderophore"

# METAGENOME ASSEMBLY
# Do Metagenome Assembly from Unmapped Fastq Files
MetagenomeAssm: 
  Activate: True
  # Use the kraken extracted reads? e.g. if taxa = 2, perform metagenome assembly on only bacterial associated reads 
  UseKrakenExtracted: False
  Threads: 14
  Memory: 0.5

# METAGENOME BINNING AND QA
MetagenomeBinning: 
  Activate: True
  Threads: 30
  # Minimum contig length required for final binning stage with metabat2
  MinimumContigLength: 1500

# Use Checkm to calculate bin statistics
CheckmBinQA: 
  Activate: True
  Threads: 8

# FINISHED! 
